services:
  app:
    build:
      context: app
      dockerfile: ./Dockerfile
    container_name: app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app

  database:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    volumes:
      - mysql:/var/lib/mysql
      - ./database/init.sql/:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  mysql:
    driver: local